### ISSUE TITLE
Switch from map to unordered_map

### ISSUE THREAD

**Issue by egorpugin** [no1msd/mstch#3]
Is is truly needed that every map is sorted by key string?
Or hash map in this case slower than sorted?

**Comment by no1msd** [comment]
I did some benchmarking, and it seems that using an std::unordered_map for the associative type in the mstch::node instead of a std::map is actually slower when the average number of elements in them are less than 100. It's about the same with ~1000, and unordered_map starts to get significantly faster above 10k elements. I guess it's because the overhead of the more complex unordered_map.

In the average use case I don't really think that the data used for rendering templates will have 10k elements per map, so I don't see the need to switch. I'm sure there are hash map implementations out there that would be faster, but unless there is a really good reason to optimize for this, I'd prefer to use standard containers as much as possible.

**Comment by egorpugin** [comment]
I see. That seems reasonable. Thanks!
